TEST_MODE = False
DEBUG_DATAGEN = False
DEBUG_EVENT_STATE = False
DEBUG_STREAMER = False
DEBUG_STATE_UPDATE = False

SERVER_PORT = 5000
REDIS_HOST = 'localhost'
REDIS_TTL_SEC = 3600  # 1 hour
ES_HOST = 'localhost'
ES_POWER_BLOCKS_INDEX = 'power_blocks'
SQL_HOST = 'localhost'

PERIOD_MS = 100  # 100 ms
